Algoritmo "semnome"
//3. Faça o fluxograma e pseudocódigo para um programa que mostre a quantidade de
//números entre 1000 e 2000 e que, quando divididos por 11, produzam resto igual a 5.
Var
  numeros,resto,calculo:inteiro



Inicio
    para numeros de 1000 ate 2000 passo 1 faca
       resto<-numeros mod 11
       se(resto=5) entao
          escreval(numeros," o resto foi 5")
       fimse
    fimpara

















Fimalgoritmo